### ISSUE TITLE
Use labels to automatically assign milestones

### ISSUE THREAD

**Issue by ghostwriter** [ghostwriter/compliance#19]
Using 3 labels to identify `major`,`minor`,`patch` changes a given PR introduces.

Using the git to identify the latest tag.

Latest version: "1.2.3"

If a PR is labeled `patch` the PR is assigned milestone "1.2.4"

If a PR is labeled `minor` the PR is assigned milestone "1.3.0"

If a PR is labeled `major` the PR is assigned milestone "2.0.0"

If a PR is labeled `{major|minir|patch}` and it already has a `{major|minir|patch}` label; it will remove and overwrite the previous label. (also updates the PRs milestone)

**Comment by ghostwriter** [comment]
```
on:
  issues:
    types: [labeled, unlabeled]
  pull_request_target:
    types: [labeled, unlabeled]
  discussion:
    types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

```
